In [ ]:
#ruta = '/content/drive/MyDrive/TUIA/Cursado1_2026'

# **NOTEBOOK CLASE 1 UNIDAD 2 - FUNDAMENTOS DE CIENCIA DE DATOS**

## ***Manipulación de datos***

In [ ]:
# Librerías
import pandas as pd

In [ ]:
# Creación de DataFrame "de juguete" para repasar Pandas
datos = pd.DataFrame({'id' : ['id1', 'id2', 'id3', 'id4', 'id5'],
              'nombre' : ['Joaquín', 'Sol', 'Alejandro', 'Bautista', 'Aldana'],
              'edad' : [31, 35, 30, 25, 28],
              'altura_m' : [1.81, 1.75, 1.71, 1.65, 1.85],
              'ciudad' : ['Rosario', 'Rosario', 'Santa Fe', 'CABA', 'Victoria']})
datos

    id     nombre  edad  altura_m    ciudad
0  id1    Joaquín    31      1.81   Rosario
1  id2        Sol    35      1.75   Rosario
2  id3  Alejandro    30      1.71  Santa Fe
3  id4   Bautista    25      1.65      CABA
4  id5     Aldana    28      1.85  Victoria

In [ ]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        5 non-null      object
 1   nombre    5 non-null      object
 2   edad      5 non-null      int64
 3   altura_m  5 non-null      float64
 4   ciudad    5 non-null      object
dtypes: float64(1), int64(1), object(3)
memory usage: 332.0+ bytes

In [ ]:
datos.dtypes

id           object
nombre       object
edad          int64
altura_m    float64
ciudad       object
dtype: object

In [ ]:
# FILTRADO

datos['ciudad'] == 'Rosario'

0     True
1     True
2    False
3    False
4    False
Name: ciudad, dtype: bool

In [ ]:
datos[datos['ciudad'] == 'Rosario']

    id   nombre  edad  altura_m   ciudad
0  id1  Joaquín    31      1.81  Rosario
1  id2      Sol    35      1.75  Rosario

In [ ]:
datos.loc[datos['ciudad'] == 'Rosario']

    id   nombre  edad  altura_m   ciudad
0  id1  Joaquín    31      1.81  Rosario
1  id2      Sol    35      1.75  Rosario

In [ ]:
datos.set_index('id', inplace = True)

In [ ]:
datos

        nombre  edad  altura_m    ciudad
id
id1    Joaquín    31      1.81   Rosario
id2        Sol    35      1.75   Rosario
id3  Alejandro    30      1.71  Santa Fe
id4   Bautista    25      1.65      CABA
id5     Aldana    28      1.85  Victoria

In [ ]:
datos.loc['id3']

nombre      Alejandro
edad               30
altura_m         1.71
ciudad       Santa Fe
Name: id3, dtype: object

In [ ]:
datos.iloc[2]

nombre      Alejandro
edad               30
altura_m         1.71
ciudad       Santa Fe
Name: id3, dtype: object

# **MANOS A LA OBRA I - Dataset `lista_personas`**

In [ ]:
datos_personas = pd.read_csv(ruta + '/datasets/lista_personas.csv')
datos_personas.head()

  Apellido     Nombre        DNI Fecha_nacimiento
0    Pedro   González  41 523661         8/4/1998
1  Joaquín  Fernández   34567895         6/6/1990
2   Silvia     Nuncia   14697454       15/12/1961
3  Luciano       Lima   28475692         2/7/1980
4     Lara      Pérez   35647892         9/4/1991

## ¿Cuántas filas y columnas tiene el dataset?

Tiene 4 colummas y 16 filas

In [ ]:
datos_personas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Apellido          16 non-null     object
 1   Nombre            16 non-null     object
 2   DNI               16 non-null     object
 3   Fecha_nacimiento  16 non-null     object
dtypes: object(4)
memory usage: 644.0+ bytes

## ¿Hay alguna columna que contenga datos faltantes?
No, no hay.

## Observá los nombres de las columnas. ¿Detectás alguna inconsistencia?

In [ ]:
datos_personas.head()

  Apellido     Nombre        DNI Fecha_nacimiento
0    Pedro   González  41 523661         8/4/1998
1  Joaquín  Fernández   34567895         6/6/1990
2   Silvia     Nuncia   14697454       15/12/1961
3  Luciano       Lima   28475692         2/7/1980
4     Lara      Pérez   35647892         9/4/1991

In [ ]:
datos_personas.rename(columns = {'Apellido' : 'Nombre', 'Nombre' : 'Apellido'}, inplace = True)
datos_personas.head()

    Nombre   Apellido        DNI Fecha_nacimiento
0    Pedro   González  41 523661         8/4/1998
1  Joaquín  Fernández   34567895         6/6/1990
2   Silvia     Nuncia   14697454       15/12/1961
3  Luciano       Lima   28475692         2/7/1980
4     Lara      Pérez   35647892         9/4/1991

## ¿Qué tipo de dato contiene cada columna? ¿Es el esperado en cada caso?

In [ ]:
datos_personas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Nombre            16 non-null     object
 1   Apellido          16 non-null     object
 2   DNI               16 non-null     object
 3   Fecha_nacimiento  16 non-null     object
dtypes: object(4)
memory usage: 644.0+ bytes

In [ ]:
datos_personas.head()

  Apellido     Nombre        DNI Fecha_nacimiento
0    Pedro   González  41 523661         8/4/1998
1  Joaquín  Fernández   34567895         6/6/1990
2   Silvia     Nuncia   14697454       15/12/1961
3  Luciano       Lima   28475692         2/7/1980
4     Lara      Pérez   35647892         9/4/1991

In [ ]:
datos_personas['Fecha_nacimiento_cod'] = pd.to_datetime(datos_personas['Fecha_nacimiento'], format = '%d/%m/%Y')
datos_personas.head()

  Apellido     Nombre        DNI Fecha_nacimiento Fecha_nacimiento_cod
0    Pedro   González  41 523661         8/4/1998           1998-04-08
1  Joaquín  Fernández   34567895         6/6/1990           1990-06-06
2   Silvia     Nuncia   14697454       15/12/1961           1961-12-15
3  Luciano       Lima   28475692         2/7/1980           1980-07-02
4     Lara      Pérez   35647892         9/4/1991           1991-04-09

In [ ]:
datos_personas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Apellido              16 non-null     object
 1   Nombre                16 non-null     object
 2   DNI                   16 non-null     object
 3   Fecha_nacimiento      16 non-null     object
 4   Fecha_nacimiento_cod  16 non-null     datetime64[ns]
dtypes: datetime64[ns](1), object(4)
memory usage: 772.0+ bytes

# **MANOS A LA OBRA II**

 ## ¿Quién es la persona de mayor edad entre las personas del dataset?

## Extraer el mes de nacimiento de cada persona en una nueva columna. ¿Cuál fue el mes con mayor cantidad de nacimientos?

In [ ]:
datos_personas['Mes_nacimiento'] = datos_personas['Fecha_nacimiento_cod'].dt.month
datos_personas.head()

,Apellido,Nombre,DNI,Fecha_nacimiento,Fecha_nacimiento_cod,Mes_nacimiento
0,Pedro,González,41 523661,8/4/1998,1998-04-08,4
1,Joaquín,Fernández,34567895,6/6/1990,1990-06-06,6
2,Silvia,Nuncia,14697454,15/12/1961,1961-12-15,12
3,Luciano,Lima,28475692,2/7/1980,1980-07-02,7
4,Lara,Pérez,35647892,9/4/1991,1991-04-09,4

In [ ]:
# Diccionario meses
meses = {
    1: 'enero', 2: 'febrero', 3: 'marzo', 4: 'abril',
    5: 'mayo', 6: 'junio', 7: 'julio', 8: 'agosto',
    9: 'septiembre', 10: 'octubre', 11: 'noviembre', 12: 'diciembre'
}

datos_personas['Mes_nacimiento_nombre'] = datos_personas['Mes_nacimiento'].map(meses)
datos_personas.head()

,Apellido,Nombre,DNI,Fecha_nacimiento,Fecha_nacimiento_cod,Mes_nacimiento,Mes_nacimiento_nombre
0,Pedro,González,41 523661,8/4/1998,1998-04-08,4,abril
1,Joaquín,Fernández,34567895,6/6/1990,1990-06-06,6,junio
2,Silvia,Nuncia,14697454,15/12/1961,1961-12-15,12,diciembre
3,Luciano,Lima,28475692,2/7/1980,1980-07-02,7,julio
4,Lara,Pérez,35647892,9/4/1991,1991-04-09,4,abril

In [ ]:
datos_personas['Mes_nacimiento_nombre'].value_counts()

Mes_nacimiento_nombre
abril         4
julio         3
diciembre     2
junio         1
octubre       1
enero         1
septiembre    1
noviembre     1
febrero       1
marzo         1
Name: count, dtype: int64