# EJERCICIO 1

PUNTO 1

In [19]:
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq
from fuzzywuzzy import fuzz

df = pd.read_excel("datasets/flete-aereo-vacunas-covid19-al-2021-06-28.xlsx", header=4)

#df.info()
#print(df.head(10))

df.rename(columns={old_name: new_name for old_name, new_name in 
zip(df.columns, [col.replace(' ', '') for col in df.columns])}, inplace=True)

#print(df.columns)

#Calculo la frecuencia de vuelos
frecuencia_vuelos = df['vuelo'].value_counts()
#print(frecuencia_vuelos)

#Calculo el porcentaje de cada vuelo
porcentaje_vuelos = (frecuencia_vuelos/df['vuelo'].count())
#print(round(porcentaje_vuelos * 100, 2))

PUNTO 2

In [8]:
#Vemos que tipo de datos tenemos en la columna vuelo
#print(df.vuelo.unique())

#Cuento los registros donde 'vuelo' es NaN (no contiene informacion). 
#(Cantidad Absurda, el df esta lleno de NaN al final, hay que limpiarlos)
registros_sin_vuelos = df['vuelo'].isna().sum()
print("antes de limpiar los NaN:", registros_sin_vuelos)

df.dropna(axis=0, thresh=3, inplace=True)
registros_sin_vuelos = df['vuelo'].isna().sum()
print("\ndespues de limpiar los NaN:", registros_sin_vuelos)

antes de limpiar los NaN: 1048508

despues de limpiar los NaN: 3

PUNTO 3

In [ ]:
print(df['factura_moneda_monto'].head(15))

#Hacer con REGEX. Repasar

0     USD 305.250,00
1     USD 302.250,00
2     USD 302.250,00
3                NaN
4     USD 303.075,00
5      USD 28.754,34
6     USD 428.000,00
7     USD 301.850,00
8     EUR 158.117,70
9     EUR 237.859,45
10    USD 301.025,00
11    USD 133.783,00
12    USD 105.084,89
13     EUR 72.134,00
14    USD 297.800,00
Name: factura_moneda_monto, dtype: str

,organismo,expediente,financiamiento,acto_conclusión,descripción,prestador,CUIT,estado,factura_nro,factura_moneda_monto,guía_nro,guía_moneda_monto,fecha_guía,vuelo,bienes_transportados,proveedor_bienes_transportados,operación,comprador_donante,origen
0,Ministerio de Salud de la Nación,EX-2020-91578184- -APN-DD#MS,Fuente Financiamiento 11,DI-2021-16691129-APN-SSGA#MS,Flete aéreo,Aerolíneas Argentinas S.A.,30-64140555-4,Cumplido,0411-00011116,"USD 305.250,00",044-44032951,"USD 679,84",2020-12-23,1061,marking,Biointegrator LLC,Adquisición,Secretaría de Acceso a la Salud,Rusia
1,Ministerio de Salud de la Nación,EX-2020-91578184- -APN-DD#MS,Fuente Financiamiento 11,DI-2021-16691129-APN-SSGA#MS,Flete aéreo,Aerolíneas Argentinas S.A.,30-64140555-4,Cumplido,0411-00011116,"USD 302.250,00",044-44032940,"USD 304.570,16",2020-12-23,1061,vaccine pharmaceuticals,Human Vaccine LLC,Adquisición,Secretaría de Acceso a la Salud,Rusia
2,Ministerio de Salud de la Nación,EX-2021-04601170- -APN-DD#MS,Fuente Financiamiento 11,DI-2021-24666588-APN-SSGA#MS,Flete aéreo,Aerolíneas Argentinas S.A.,30-64140555-4,Cumplido,0411-00011206,"USD 302.250,00",044-44032973,"USD 302.250,00",2021-01-15,1061,vaccine pharmaceuticals,Human Vaccine LLC,Adquisición,Secretaría de Acceso a la Salud,Rusia
3,Ministerio de Salud de la Nación,EX-2021-08460702- -APN-DD#MS,Fuente Financiamiento 11,DI-2021-24639513-APN-SSGA#MS,Flete aéreo,Aerolíneas Argentinas S.A.,30-64140555-4,Cumplido,0411-00011296,NaN,044-44032984,"USD 268.655,94",2021-01-29,1063,vaccine pharmaceuticals,Human Vaccine LLC,Adquisición,Secretaría de Acceso a la Salud,Rusia
4,Ministerio de Salud de la Nación,EX-2021-13211127- -APN-DD#MS,Fuente Financiamiento 11,DI-2021-24642675-APN-SSGA#MS,Flete aéreo,Aerolíneas Argentinas S.A.,30-64140555-4,Cumplido,0411-00011370,"USD 303.075,00",044-44032995,"USD 303.075,00",2021-02-11,1065,vaccine pharmaceuticals,Human Vaccine LLC,Adquisición,Secretaría de Acceso a la Salud,Rusia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048566,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN
1048567,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN
1048568,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN
1048569,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN
1048570,NaN,NaN,Fuente Financiamiento 11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN

PUNTO 4

In [11]:
# Calculo la cantidad de vuelos que hay con origen en rusia y con origen en china. 
vuelos_china_rusia = len(df[(df['origen'] == 'Rusia')|(df['origen'] == 'China')])

# Calculo y muesto el porcentaje sobre el total de vuelos
print(f"El porcentaje de vuelos con origen desde Rusia y China es: {round(vuelos_china_rusia / len(df) * 100, 2)}%")

El porcentaje de vuelos con origen desde Rusia y China es: 95.45%

PUNTO 5

In [ ]:
# Utilizo las funciones maximo/minimo para mostrar cual fue el vuelo mas reciente/antiguo. 
print("Vuelo mas reciente: ", df['fecha_guía'].max())
print("Vuelo mas antiguo: ", df['fecha_guía'].min())

# Cantidad de dias entre vuelos, calculado solamente haciendo la diferencia entre lo que nos devuelven
# las funciones max/min
print("Cantidad de dias entre vuelos: ", max(df['fecha_guía']) - min(df['fecha_guía']))

Vuelo mas reciente:  2021-06-22 00:00:00
Vuelo mas antiguo:  2020-12-23 00:00:00
Cantidad de dias entre vuelos:  181 days 00:00:00

PUNTO 6

In [ ]:
# Antes convertimos la columna 'vuelo' a tipo str
df['vuelo'] = df['vuelo'].astype(str)

# Escribimos el DataFrame en formato Parquet
df.to_parquet('vuelos_covid.parquet')               #me tira error


# Utilizando PyArrow

# Convertimos el DataFrame en una tabla de pyArrow
tabla = pa.Table.from_pandas(df)

# Escribimos el archivo Parquet
pq.write_table(tabla, 'datos.parquet')

ArrowKeyError: No type extension with name arrow.py_extension_type found

# EJERCICIO 10

In [ ]:
dfventas = pd.read_excel("datasets/ventas.xlsx")
dfclientes = pd.read_excel("datasets/clientes_base.xlsx")

dfventas.head(20)

<class 'pandas.DataFrame'>
RangeIndex: 42 entries, 0 to 41
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id_venta             42 non-null     str
 1   nombre_cliente       42 non-null     str
 2   producto             42 non-null     str
 3   cantidad             42 non-null     int64
 4   precio_usd_producto  42 non-null     int64
dtypes: int64(2), str(3)
memory usage: 1.8 KB

In [ ]:
#df2.info()
dfclientes.head(15)

    id_cliente       nombre_cliente         ciudad                    email
0            1      Lucia Fernandez    Villa María         luciaf2@mail.com
1            2         Carlos Gómez        Mendoza     carlosgomez@mail.com
2            3         Andrés Pérez     Corrientes        andresp3@mail.com
3            4        Roberto Gómez        Rosario          rgomez@mail.com
4            5  Roberto Gómez Acuña     Corrientes         robgoac@mail.com
5            6          Juana Pérez          Salta      juanaperez@mail.com
6            7      Lucía Hernández       Santa Fe  luciahernandez@mail.com
7            8  Andrés Pérez Gollán  Mar del Plata         andresp@mail.com
8            9         Miguel Ángel        Neuquén     miguelangel@mail.com
9           10       Marcos Rupetti      Bariloche         marcosg@mail.com
10          11       Laura Martínez       San Juan          lauram@mail.com
11          12        Ana Fernández        Posadas    anafernandez@mail.com
12          13       Karla González        Mendoza         gonz-ka@mail.com
13          14       Lucía Caparrós        Rosario          luciah@mail.com
14          15         Miguel Angel         Paraná    miguelangel2@mail.com

PUNTO 1

In [ ]:
ventas_ipad_mac = dfventas[dfventas['producto'].str.contains('iPad|MacBook')]

#print(ventas_ipad)
ventas_ipad_mac['monto'] = ventas_ipad_mac['precio_usd_producto'] * ventas_ipad_mac['cantidad']

monto_total = ventas_ipad_mac['monto'].sum()

print(monto_total)
ventas_ipad_mac

6663

,id_venta,nombre_cliente,producto,cantidad,precio_usd_producto,monto
4,C5,Mariano Rodriguéz,iPad Pro,1,1099,1099
6,C7,Maria Garcìa,MacBook Air,1,1249,1249
15,C16,Laura Martínez,iPad mini,1,559,559
18,C19,Andres Pérrez,MacBook Pro,1,1999,1999
22,C23,Andres Péres,iPad Air,2,599,1198
38,C39,Juan Perez,iPad mini,1,559,559

PUNTO 2

In [ ]:
union = pd.merge(dfventas, dfclientes, on='nombre_cliente')

# Se nota que en el dataframe dfventas hay 42 entradas a diferencia del dataframe resultante 
# que tiene solo 14 entradas.

dfventas.info()
dfclientes.info()

<class 'pandas.DataFrame'>
RangeIndex: 42 entries, 0 to 41
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id_venta             42 non-null     str
 1   nombre_cliente       42 non-null     str
 2   producto             42 non-null     str
 3   cantidad             42 non-null     int64
 4   precio_usd_producto  42 non-null     int64
dtypes: int64(2), str(3)
memory usage: 1.8 KB
<class 'pandas.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_cliente      36 non-null     int64
 1   nombre_cliente  36 non-null     str
 2   ciudad          36 non-null     str
 3   email           36 non-null     str
dtypes: int64(1), str(3)
memory usage: 1.3 KB

PUNTO 3

In [ ]:
porcentaje = round((union['nombre_cliente'].count() / dfclientes['nombre_cliente'].count()) * 100, 2)

print(porcentaje, "%")

38.89 %